name: Deploy

on:
  push:
    branches:
      - master

jobs:

  building_flask_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Action
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flask-app-cicd" # Heroku app name
          heroku_email: "chaitanyagaikwad47@gmail.com"
          appdir: "application/"
          usedocker: true